### ISSUE TITLE
Python Software won't start

### ISSUE THREAD

**Issue by UnlimitedChild** [sandboxie-plus/Sandboxie#1473]
Hello,

"All DRM Removal" was successfully launched in a sandbox before the source code was opened, in the current version this program is crashing.

Download link: https://www.epubor.com/drm-removal-tools.html

Windows-10-10.0.19041-SP0_AMD64
AllDRMRemoval v1.0.17.507
Traceback (most recent call last):
  File "main.py", line 26, in main
  File "c:\miniconda3\envs\py34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ui\dlgMain.py", line 8, in <module>
  File "c:\miniconda3\envs\py34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "module\device.py", line 8, in <module>
ImportError: cannot import name 'KSN_FILE'

**Comment by DavidXanatos** [comment]
starts just fine in the latesr version
